### PR TITLE
Control passing trace header to down stream services

### PR DESCRIPTION
**Pull request by ma2gedev**
Down stream services may contain uncontrollable services such as third party services.
We would not like to send trace header for those services.
So I think it's useful to control passing trace header.

NOTICE: I have not confirmed this change worked on AWS X-Ray. I will notice you after confirmation.

### CODE REVIEW

**Comment by taiki45** [comment]
I'm thinking about your use case.

1. What are actual problems around sending trace headers to third-party servers?
2. The current implementation is a kind of "blacklist method". But in this case, "whitelist method" seems proper than blacklist one: allow trusted hosts and only send to them.

**Comment by ma2gedev** [comment]
Thank you for your response.

> 1. What are actual problems around sending trace headers to third-party servers?

Basically third party services does not need trace headers.
We do not want to send much unnecessary information. They can ignore it, though.

> 2. The current implementation is a kind of "blacklist method". But in this case, "whitelist method" seems proper than blacklist one: allow trusted hosts and only send to them.

Thank you for your feedback. I think so too. I changed the code according to your suggestion.

**Comment by ma2gedev** [comment]
I have confirmed latest change worked on AWS X-Ray.

**Comment by taiki45** [comment]
>We do not want to send much unnecessary information. They can ignore it, though.

Are there any security risks? It seems the trace headers don't have any secrets or secure information: http://docs.aws.amazon.com/xray/latest/devguide/xray-concepts.html#xray-concepts-tracingheader

**Comment by ma2gedev** [comment]
I'm not a security expert but probably there is no security risk as you say. My concern is not about security risks.

My concern is that trace header is required only by servers that we manage.
Third party cannot do anything if servers that they manage receive trace header.
Therefore, I do not want to send trace headers if it is not needed in such a case.

Please let me know if my understanding is wrong.

**Comment by taiki45** [comment]
>Third party cannot do anything if servers that they manage receive trace header.

Yes, and they can just ignore the trace header as you wrote before. So please let me ask again, why do you want to stop sending them? What is a problem behind?

**Comment by ma2gedev** [comment]
I thought that sending unnecessary header is the problem but this was my misunderstanding.
I asked my colleague whether it is a problem because I thought my idea might be wrong after saw your latest comment.
They said it isn't a problem if the header size is not large.

So I will close this pull request.
Sorry to waste your time. 🙇  And thank you correcting me.

**Comment by taiki45** [comment]
Thank you for your suggestion 👍

**Pull request closed without merging**
